### ISSUE TITLE
Make plugin compatible with latest Phonegap 3+ and Xcode5

### ISSUE THREAD

**Issue by jurisv** [jcesarmobile/PhonegapOCRPlugin#7]
[INF] [shellscript] [phonegap] compiling iOS...
[INF] [shellscript]    [error] An error occurred while building the ios project.** BUILD FAILED **
[INF] [shellscript] 
[INF] [shellscript] 
[INF] [shellscript] The following build commands failed:
[INF] [shellscript] 	Check dependencies
[INF] [shellscript] (1 failure)
[INF] [shellscript] 2014-02-10 11:44:38.247 xcodebuild[43314:7103]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-3575/Xcode3Sources/XcodeIDE/Frameworks/DevToolsBase/pbxcore/SpecificationTypes/XCGccMakefileDependencies.m:78
[INF] [shellscript] Details:  Failed to load dependencies output contents from ``/Users/juris/customers/zzz/YardVehicleMgmt/phonegap/platforms/ios/build/Railcar.build/Debug-iphonesimulator/Railcar.build/Objects-normal/i386/claseAuxiliar.d''''''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “claseAuxiliar.d” couldn’t be opened because there is no such file." UserInfo=0x7fa3e5004ce0 '{'NSFilePath=/Users/juris/customers/zzz/YardVehicleMgmt/phonegap/platforms/ios/build/Railcar.build/Debug-iphonesimulator/Railcar.build/Objects-normal/i386/claseAuxiliar.d, NSUnderlyingError=0x7fa3e17aee30 "The operation couldn’t be completed. No such file or directory"'}'. User info: '{'
[INF] [shellscript]     NSFilePath = "/Users/juris/customers/zzz/YardVehicleMgmt/phonegap/platforms/ios/build/Railcar.build/Debug-iphonesimulator/Railcar.build/Objects-normal/i386/claseAuxiliar.d";
[INF] [shellscript]     NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
[INF] [shellscript] '}'.
[INF] [shellscript] Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, F) [F = <lambda at /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-3575/Xcode3Sources/XcodeIDE/Frameworks/DevToolsBase/pbxcore/SpecificationTypes/XCGccMakefileDependencies.m:168:73>]
[INF] [shellscript] Thread:   <NSThread: 0x7fa3e17eb490>'{'name = (null), num = 9'}'
[INF] [shellscript] Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
[INF] [shellscript] ** BUILD FAILED **

**Comment by sbasi5576** [comment]
@jurisv - do you have the complete instructions documented anywhere?

**Comment by jurisv** [comment]
@sbasi5576 I did not document anything. This would be irrelevant anyways as you have to use XCode 7 to build plugin for completely different version of cordova.

**Comment by jurisv** [comment]
This ticket is obsolete, so closing.
Replacement https://github.com/jcesarmobile/PhonegapOCRPlugin/issues/8
