### ISSUE TITLE
XCode 7 and cordova 6+

### ISSUE THREAD

**Issue by lidyaagustina** [jcesarmobile/PhonegapOCRPlugin#8]
Hello,

Im new in this.

I tried it on XCode 7 and cordova 6, and also add this to config.xml:

  <feature name="com.jcesarmobile.OCRPlugin">
      <param name="ios-package" value="OCRPlugin" />
  </feature>
  OR
  <plugin name="com.jcesarmobile.OCRPlugin" value="OCRPlugin" />

Both still gave me:
ERROR: Plugin 'com.jcesarmobile.OCRPlugin' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.

Could you advice me what could possibly be wrong?

Thanks.

Lidya

**Comment by jcesarmobile** [comment]
The plugin is not compatible with cordova 3.x.x or greater, it needs and update and I don't have time to do it, sorry.

**Comment by lidyaagustina** [comment]
Hello Thanks for your prompt reply.

Could you point me to the correct directly on how i can do it myself? Is it very complex?

Thanks.

Lidya

**Comment by jcesarmobile** [comment]
Maybe the info on https://github.com/jcesarmobile/PhonegapOCRPlugin/issues/7 can help you

**Comment by jcesarmobile** [comment]
This plugin is not maintained, you can check this new plugin https://github.com/jcesarmobile/cordova-plugin-tesseract-ocr
