### ISSUE TITLE
#include "baseapi.h" not found

### ISSUE THREAD

**Issue by edvenkat** [jcesarmobile/PhonegapOCRPlugin#9]
I am getting #include "baseapi.h" not found please advice.....

**Comment by jcesarmobile** [comment]
Did you select "copy items into destination group" when dragged dependencies folder to Xcode?
Is dependencies folder yellow?

**Comment by edvenkat** [comment]
I don't see baseapi.h

**Comment by jcesarmobile** [comment]
Sorry, I asked a question and you don't answer, so I'm closing the issue. Read the README.md and follow the instructions.
